export default 
[
    {
      "type":"group",
      "title":"Thematische lagen",
      "sublayers":[
        {
          "type":"group",
          "title":"WMS",
          "sublayers":[
            {
              "title":"PDOK Luchtfoto",
              "type":"wms",
              "layerInfo":{
                "id":"pdokluchtfoto",
                "type":"raster",
                "source":{
                  "type":"raster",
                  "tileSize":256,
                  "tiles":[
                    "https://geodata.nationaalgeoregister.nl/luchtfoto/rgb/wms?bbox={bbox-epsg-3857}&format=image/png&service=WMS&version=1.1.1&request=GetMap&srs=EPSG:3857&width=256&height=256&styles=default&layers=Actueel_ortho25&transparent=true"
                  ],
                  "attribution":"PDOK"
                }
              }
            },
            {
              "title":"Blaeu",
              "type":"wms",
              "layerInfo":{
                "id":"blaeu",
                "type":"raster",
                "metadata":{
                  "legendurl":"https://mapserver.edugis.nl/legends/nederland/belgica-logo.jpg"
                },
                "minzoom":5.5,
                "maxzoom":12.5,
                "source":{
                  "type":"raster",
                  "tileSize":256,
                  "tiles":[
                    "https://t1.edugis.nl/tiles/tilecache.py?map=maps/edugis/cache/blaeu.map&LAYERS=Nederland%2017e%20eeuw%20(Blaeu)&TRANSPARENT=true&FORMAT=image%2Fpng&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&STYLES=&SRS=EPSG%3A3857&BBOX={bbox-epsg-3857}&WIDTH=256&HEIGHT=256",
                    "https://t2.edugis.nl/tiles/tilecache.py?map=maps/edugis/cache/blaeu.map&LAYERS=Nederland%2017e%20eeuw%20(Blaeu)&TRANSPARENT=true&FORMAT=image%2Fpng&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&STYLES=&SRS=EPSG%3A3857&BBOX={bbox-epsg-3857}&WIDTH=256&HEIGHT=256"
                  ],
                  "attribution":"EduGIS"
                }
              }
            }
           ]
        }
      ]
    }
]